### ISSUE TITLE
[Upstream] Halite v5 Released (Security Improvements)

### ISSUE THREAD

**Issue by paragonie-security** [adriansuter/php-crypto-suite#2]
Halite version 5 was released today, which contains a few security improvements and may be worth the effort to upgrade to v5.

https://github.com/paragonie/halite/releases/tag/v5.0.0

(You're receiving this issue because Packagist says you depend on Halite.)

**Comment by adriansuter** [comment]
Currently we need php 7.4 support - so we can not upgrade halite. But sooner or later, we should.

**Comment by adriansuter** [comment]
Addressed by #3 .
